# Generated by Django 6.0.6 on 2026-06-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(default='dineflow@paytm', help_text='Your UPI ID, e.g. dineflow@paytm', max_length=100)),
                ('merchant_name', models.CharField(default='DineFlow', help_text='Merchant name shown on UPI apps', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UPI Settings',
                'verbose_name_plural': 'UPI Settings',
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_verification', 'Pending Verification'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
    ]
